---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.0'
      jupytext_version: 0.8.6
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

# Exploration of Loan Data from Prosper 
## by Jannis Müller



## Investigation Overview

> Describe the overall goals of your presentation here.

## Dataset Overview

> This data set contains 113,937 loans with 81 variables on each loan, including loan amount, borrower rate (or interest rate), current loan status, borrower income, and many others

```{python slideshow={'slide_type': 'skip'}}
# import all packages and set plots to be embedded inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

# %matplotlib inline

# suppress warnings from final output
import warnings
warnings.simplefilter("ignore")
```

```{python slideshow={'slide_type': 'skip'}}
# load in the dataset into a pandas dataframe

```

> Note that the above cells have been set as "Skip"-type slides. That means
that when the notebook is rendered as http slides, those cells won't show up.


## (Visualization 1)

> Write a comment about your visualization here. The visualization should be in
the next cell, as a sub-slide type. Make sure your visualizations are polished!

```{python slideshow={'slide_type': 'subslide'}}

```

## (Visualization 2)

> You should have at least three visualizations in your presentation,
but feel free to add more if you'd like!

```{python slideshow={'slide_type': 'subslide'}}

```

## (Visualization 3)



```{python slideshow={'slide_type': 'subslide'}}

```

> Once you're ready to finish your presentation, check your output by using
nbconvert to export the notebook and set up a server for the slides. From the
terminal or command line, use the following expression:
> > `jupyter nbconvert <file_name>.ipynb --to slides --post serve --template output_toggle`

> This should open a tab in your web browser where you can scroll through your
presentation. Sub-slides can be accessed by pressing 'down' when viewing its parent
slide. Make sure you remove all of the quote-formatted guide notes like this one
before you finish your presentation!

```{python}

```
