---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.0'
      jupytext_version: 0.8.6
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

# Exploration Loan Data from Prosper
## by Jannis

## Preliminary Wrangling

This data set contains 113,937 loans with 81 variables on each loan, including loan amount, borrower rate (or interest rate), current loan status, borrower income, and many others

```{python}
# import all packages and set plots to be embedded inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
import requests
import io

# %matplotlib inline
pd.set_option('display.max_columns', 50)
```

```{python}
# Loading the dataset with request libary and saving dataset as CSV file
url = 'https://s3.amazonaws.com/udacity-hosted-downloads/ud651/prosperLoanData.csv'
response = requests.get(url).content
data = pd.read_csv(io.StringIO(response.decode('utf-8')))
data.to_csv('loan_data.csv')
```

```{python}
# creating new data frame called loan_data
loan_data = pd.read_csv('loan_data.csv')
loan_data.head()
```

```{python}
# high-level overview of data shape and composition
print(loan_data.shape)
print(loan_data.dtypes)
```

### The structure of the dataset

The Data set contains 113,937 loans (rows) with 81 variables (columns) on each loan. Most variables are integers (numeric) or strings (objects). But the dataset also has some categorical variables: for example EmploymentStatus, ProsperScore, Term, IncomeRange


### Main features of interest in the dataset

The huge dataset with a lot of informaton (81 variables) allows me to have deeper look at the question what factors affect a loan’s outcome status (Cancelled, Chargedoff, Completed, Current, Defaulted, FinalPaymentInProgress, PastDue)?

This is a very critical question for banks and loan companies in order to minimize the default risk and and to set the right interest rate (including setting a proper risk premium).

This investigation might help to find out what factors predict the outcome of a loan best. 
  



### Features in the dataset that will help support the investigation

The factors that have the most influence on predicting the outcome of a loan and therefore of most interest are:

 - Term (The length of the loan expressed in months)
 - ProsperScore (custom risk score)
 - EmploymentStatus (The employment status of the borrower)
 - MonthlyLoanPayment (The scheduled monthly loan payment)
 - IncomeRange (The income range of the borrower at the time the listing was created)
 - BorrowerRate (The Borrower's interest rate for this loan)
 - LoanOriginalAmount (The origination amount of the loan)
 - OpenCreditLines (Number of open credit line)
 - TotalProsperPaymentsBilled (number of on time payments the borrower made on Prosper loans at the time they created this listing)
 - Recommendations (Number of recommendations the borrower had at the time the listing was created)


Whereby I expect  to have  `ProsperScore`, `TotalProsperPaymentsBilled`, `EmploymentStatus`, `BorrowerRate`,  (high interest rate are associated with higher default risk) and `Income Range`  have  the strongest effect on the loan's outcome status.
 


#### In the first step I will create a copy of the dataset with the variables of interest

```{python}
# create a copy of the dataset
loan_data_clean = loan_data.copy()
# include all variables that are needed in the investigation in the clean copy
loan_data_clean = loan_data_clean[['ListingKey', 'LoanStatus', 'Term','ProsperScore','EmploymentStatus', 'MonthlyLoanPayment', 'Recommendations','BorrowerAPR','BorrowerRate','LoanOriginalAmount', 'OpenCreditLines','StatedMonthlyIncome','TotalProsperPaymentsBilled', 'IncomeRange']]
#getting a overview over the new dataset
print(loan_data_clean.head())
print(loan_data_clean.info())
```

#### Since the variables EmploymentStatus, ProsperScore, Term, IncomeRange are basically categorical variabels, I will change their datatype till categorical

```{python}
# changing the datatypes till categorical
loan_data_clean['ProsperScore'] = loan_data_clean['ProsperScore'].astype('category')
loan_data_clean['Term'] = loan_data_clean['Term'].astype('category')
loan_data_clean['IncomeRange'] = loan_data_clean['IncomeRange'].astype('category')
loan_data_clean['EmploymentStatus'] = loan_data_clean['EmploymentStatus'].astype('category')
loan_data_clean['LoanStatus'] = loan_data_clean['LoanStatus'].astype('category')
print(loan_data_clean.info())
```

## Univariate Exploration

I'll start by looking at the distribution of the main variable of interest
 - ProsperScore 
 - TotalProsperPaymentsBilled
 - BorrowerRate
 - EmploymentStatus
 - IncomeRange


Source for all interpretations:
https://www.dummies.com/education/math/statistics/statistics-workbook-for-dummies-cheat-sheet/

Diamonds Data Exploration- Example Project


> In this section, investigate distributions of individual variables. If
you see unusual points or outliers, take a deeper look to clean things up
and prepare yourself to look at relationships between variables.





> Make sure that, after every plot or related series of plots, that you
include a Markdown cell with comments about what you observed, and what
you plan on investigating next.

```{python}
# getting a first overview over the variable LoanStatus
print(loan_data_clean.LoanStatus.describe())
print(loan_data_clean.LoanStatus.value_counts())
```

```{python}
# bar chart LoanStatus (The current status of the loan: Cancelled, Chargedoff, Completed, Current, Defaulted, FinalPaymentInProgress, PastDue)
base_color = sb.color_palette()[0]
sb.countplot(data = loan_data_clean, x = 'LoanStatus', color = base_color)
plt.xlabel('Current Status of the Loan')
plt.xticks(rotation = 22);
```

In the next step I will transform the past due to just one.. since I mostly interested if a loan is past due and not for how long the loan is overdue. 

```{python}
# replacing Past Due (1-15 days), Past Due (31-60 days) etc. with just Past Due
loan_data_clean['LoanStatus'] = loan_data_clean['LoanStatus'].replace(['Past Due (1-15 days)', 'Past Due (31-60 days)','Past Due (61-90 days)','Past Due (91-120 days)','Past Due (16-30 days)','Past Due (>120 days)'],'Past Due')
loan_data_clean['LoanStatus'] = loan_data_clean['LoanStatus'].replace('FinalPaymentInProgress','InProgress')
print(loan_data_clean.LoanStatus.value_counts())
print(loan_data_clean.info())
```

```{python}
# plotting the bar chart of LoanStatus again
base_color = sb.color_palette()[0]
sb.countplot(data = loan_data_clean, x = 'LoanStatus', color = base_color, order = loan_data_clean['LoanStatus'].value_counts().index )
plt.xlabel('Current Status of the Loan')
plt.xticks(rotation = 35);
```

#### Most of the loans are current or completed. However there are a fairly significant number of loans that are charged off, defaulted or past due. 

```{python}
# getting a first overview over the variable ProsperScore
print(loan_data_clean.ProsperScore.describe())
print(loan_data_clean.ProsperScore.value_counts())
```

```{python}
# Bar Chart ProsperScore (custom risk score built using historical Prosper data)
# The score ranges from 1-10, with 10 being the best, or lowest risk score)

sb.countplot(data = loan_data_clean, x = 'ProsperScore', color = base_color, order = loan_data_clean['ProsperScore'].value_counts().index)
plt.xlabel('Prosper Score (from 1-10, with 10 being the best)');
```

The bar chart shows that there are customers in the data set that have a score of 11 which should not be possible since the score just ranges from 1-10 which needs to be cleaned in the next step

```{python}
# I will exclude all customers with a Prosper Score of 11
loan_data_clean = loan_data_clean[loan_data_clean['ProsperScore'] != 11]
#dubbel check if the operation was succesful
loan_data_clean[loan_data_clean['ProsperScore'] == 11]
```

```{python}
# now I will again plot the bar chart
sb.countplot(data = loan_data_clean, x = 'ProsperScore', color = base_color, order = loan_data_clean['ProsperScore'].value_counts().index)
plt.xlabel('Prosper Score (from 1-10, with 10 being the best)');
```

#### Most of the borrower have a fairly low Prosper Score of 4 (custom risk score) while the majority of the customer have a score between 5-8. You can also see that even customers with the low risks score of 1 or 2 did get a loan from Prosper. Furthermore, not many borrowers received the highest score of 10

```{python}
# getting a first overview over the TotalProsperPaymentsBilled
loan_data.TotalProsperPaymentsBilled.describe()
```

```{python}
# Histogramm TotalProsperPaymentsBilled (Number of on time payments)
binsize = 0.5
bins = np.arange(loan_data_clean.TotalProsperPaymentsBilled.min(), loan_data_clean.TotalProsperPaymentsBilled.max()+binsize, binsize)

plt.figure(figsize=[10, 5])
plt.hist(data = loan_data_clean, x = 'TotalProsperPaymentsBilled', bins = bins)
plt.xlabel('Number of on time payments')
plt.ylabel('Count')
plt.xticks([0,5,10,20,30,35,40,50,60,70,80,90,100,110,120,130,140,150])
plt.show()
```

#### The distribution of the Number of on time payments is long-tailed with two peaks: 9 and 35. It is interesting to see that the distribution is right-skewed with most of the values on the lower end and fewer values on the higher end. But we observe a second uprise between 30-36. This would make the distribution roughly bi-modial. On the first view it therefore seems like that most of the borrowers had missed to pay some of the monthly payments on time.

```{python}
# getting a first overview over the variable BorrowerRate
loan_data.BorrowerRate.describe()
```

```{python}
# Histogramm  BorrowerRate (Borrower's interest rate for this loan)
binsize = 0.005
bins = np.arange(loan_data.BorrowerRate.min(), loan_data.BorrowerRate.max()+binsize, binsize)

plt.figure(figsize=[8, 5])
plt.hist(data = loan_data_clean, x = 'BorrowerRate', bins = bins)
plt.xlabel('Interest Rate')
plt.ylabel('Count')
plt.xticks([0.0,0.1,0.15,0.2,0.25,0.3,0.35,0.4,0.45,0.5])
plt.show()
```

#### One can see in the histogramm that most of the borrowers have an interest rate between of 0.1 and 0.25, but with a peak at around 0.33. 

```{python}
# getting a first overview over the variable IncomeRange
print(loan_data.IncomeRange.describe())
print(loan_data.IncomeRange.value_counts())

```

```{python}
#Bar chart of the variable IncomeRange(The income range of the borrower at the time the listing was created)

sb.countplot(data= loan_data_clean, x= 'IncomeRange', color= base_color, order=loan_data_clean['IncomeRange'].value_counts().index)
plt.xticks(rotation=25)
plt.xlabel('Income Range ($)')
plt.ylabel('Count');
```

#### The income range of the borrowers shows that most of the loans where give to customers with a income between 25,000 and 74,999 which indicates that the borrowers are mostly middle-class (https://www.cnbc.com/2018/09/26/how-many-americans-qualify-as-middle-class.html). However, there are a fairly high number of borrowers that earns more than 75,000. One can also see that people that are not employed, not displayed their income or have an income of 0 received a loan from Prosper as well. They might be other criterias than income that qualifies one to get a loan at Prosper.

```{python}
# getting a first overview over the variable EmploymentStatus
loan_data_clean.EmploymentStatus.describe()
```

```{python}
# plotting EmploymentStatus (The employment status of the borrower at the time they posted the listing) 
sb.countplot(data= loan_data_clean, x= 'EmploymentStatus', color= base_color, order=loan_data_clean['EmploymentStatus'].value_counts().index)
plt.xticks(rotation=25)
plt.xlabel('Employment Status')
plt.ylabel('Count');
```

#### As expected are most of the borrowers employed of some kind (full-time, part-time, self-emplpoyed) but the data shows that even unemployed and retired persons could get a loan.


#### Now I also will plot the remainig factors:

 - Term                                       
 - Recommendations                   
 - BorrowerAPR                                    
 - OpenCreditLines
 - LoanOriginalAmount 
 - MonthlyLoanPayment
               
  

```{python}
# getting a first overview over the variable Term
print(loan_data_clean.Term.describe())
print(loan_data_clean.Term.value_counts())
```

```{python}
# Bar chart of the variable Term (The length of the loan expressed in months)
sb.countplot(data=loan_data_clean, x='Term', color=base_color, order = loan_data_clean['Term'].value_counts().index)
plt.xlabel('Term of the loan (month)');

```

```{python}
loan_data_clean.LoanOriginalAmount.mean()
```

#### Most of the loans have of length of 36 months, followed by 60 months while just a small amounts of loans have the minium lenght of 12 months. The fact that most of the loans have a length of just 36 months might correlated to the fact the average loan amount is around 8200 dollar which can be paid back quick. 

```{python}
# getting a first overview over the variable BorrowerAPR
print(loan_data_clean.Recommendations.describe())
print(loan_data_clean.Recommendations.value_counts())
```

```{python}
# plotting Recommendations(Number of recommendations the borrower had at the time of the loan)
sb.countplot(data=loan_data_clean, x = 'Recommendations', color = base_color);
```

Since most of the data is next to y axis, there might be strong outliers within the higher values

```{python}
# identifying outliers based on the plot
Recommendations_outliers = loan_data_clean['Recommendations'] > 5
print(Recommendations_outliers.sum())
print(loan_data_clean.loc[Recommendations_outliers,:])
```

Since the customers with more than 5 recommendations also have a high number of open credit lines (this might be the reason for high recommendations), the outliers are not errors in the data set.


#### One can see that most of the borrowers had 0 recommendations which suggest that the recommendations play a small role in the evalutation of a loan request.

```{python}
# getting a first overview over the variable OpenCreditLines
loan_data_clean.OpenCreditLines.describe()
```

```{python}
# Histogramm OpenCreditLines (Number of open credit lines at the time the credit profile was pulled)
binsize = 0.5
bins = np.arange(0, loan_data_clean.OpenCreditLines.max()+binsize, binsize)

plt.figure(figsize=[8, 5])
plt.hist(data = loan_data_clean, x = 'OpenCreditLines', bins = bins)
plt.xlabel('Open Credit Lines')
plt.ylabel('Count')
plt.xticks([0,5,10,15,20,25,30,35,40,45,50])
plt.show()
```

#### The distribution is long-tailed and right skewed with most borrowers having between 5 and 15 open credit lines. This sounds much but without having information more information of the amount of the loans, it is hard to give a more detailed statement


```{python}
# getting a first overview over the variable LoanOriginalAmount
print(loan_data_clean.LoanOriginalAmount.describe())
print(loan_data_clean.LoanOriginalAmount.value_counts().head(20))
```

```{python}
# Histogramm LoanOriginalAmount (The origination amount of the loan)
binsize = 400
bins = np.arange(0, loan_data_clean.LoanOriginalAmount.max()+binsize, binsize)

plt.figure(figsize=[8, 5])
plt.hist(data = loan_data_clean, x = 'LoanOriginalAmount', bins = bins)
plt.xlabel('Amount of the Loan')
plt.ylabel('Count')
plt.xticks([0,2500,5000,7500,10000,12500,15000,17500,20000,22500,25000,30000,35000], rotation=25)
plt.show()
```

#### The distribution has serval peaks at around 4,000, 10,000 and 15,000. But most of the values are in the lower end between 2500 and 10,000. The most loaned amounts are 4,000 and 15,000. Its a little bit suprising that the two most loaned amounts have such a difference in terms of the loan amount. One would expect one peak but maybe Prosper targets several customer groups.

```{python}
# getting a first overview over the variable MonthlyLoanPayment
print(loan_data_clean.MonthlyLoanPayment.describe())
```

```{python}
# Histogramm MonthlyLoanPayment (scheduled monthly loan payment)
binsize = 10
bins = np.arange(loan_data_clean.MonthlyLoanPayment.min(), loan_data_clean.MonthlyLoanPayment.max()+binsize, binsize)

plt.figure(figsize=[8, 5])
plt.hist(data = loan_data_clean, x = 'MonthlyLoanPayment', bins = bins)
plt.xlabel('Monthly Loan Payment')
plt.ylabel('Count')
plt.xticks([0,200,400,600,800,1000,1200,1400,1600,1800,2000])
plt.show()
```

#### The distribution is right skrewed and long-tailed with a lot of loans with small montly payments. The peak is at around 200. A strange observation is the fact that around 1000 loans have a monthly payment of 0 which doesnt really make sense but might be related to some special arrangement (for example: the customer does not need to pay back the loan during the first 6 months). Therefore, I decided to the keep these values in the dataset.


### Discussion of the distributions of the variables of interest. 


#### 1. Distributions

 - Most of the loans are current or completed. However there are a fairly significant number of loans that are    
   charged off, defaulted or past due. 
 - The income range of the borrowers shows that most of the loans where give to customers with a income between  
   25,000 and 74,999 which indicates that the borrowers are mostly middle-class.

 - Most of the borrower have a fairly low Prosper Score of 4 (custom risk score) while the majority of the customer   
   have a score between 5-8. You can also see that even customers with the low risks score of 1 or 2 did get a loan   
   from Prosper. Furthermore, not many borrowers received the highest score of 10.

 - The distribution of the lenght of the loan (Term) shows that most of the loans have of length of 36 months,  
   followed by 60 months while just a small amounts of loans have the minium lenght of 12 months.

 - The distribution of the Number of on time payments is long-tailed with two peaks: 9 and 35. It is interesting to  
   see that the distribution is right-skewed with most of the values on the lower end and fewer values on the higher    end. But we observe a second uprise between 30-36. This would make the distribution roughly bi-modial. On the   
   first view it therefore seems like that most of the borrowers had missed to pay some of the monthly payments on  
   time.

 - The distribution of the loan amount has serval peaks at around 4,000, 10,000 and 15,000. But most of the values  
   are in the lower end between 2500 and 10,000.

 - The distribution of the open credit line is long-tailed and right skewed with most borrowers having between 5 and    15 open credit lines.


#### 2. Unusual distributions
 - One can also see in the distribution of the Employment status that people that are not employed, not displayed  
   their income or have an income of 0 received a loan from Prosper as well. They might be other criterias than  
   income that qualifies one to get a loan at Prosper.
 - it was a little bit suprising that the distribution of the loan amounts has several peaks: the two most loaned  
   amounts (the two highest peaks in the distribution, 4000 & 15000) have such a difference in terms of the loan  
   amount. One would expect one peak; but maybe Prosper targets several customer groups
 - As expected are most of the borrowers employed of some kind (full-time, part-time, self-emplpoyed) but the data 
   shows that even unemployed and retired persons could get a loan.

#### 3.  tidy, adjust, or change the form of the data
 - Since the variables EmploymentStatus, ProsperScore, Term, IncomeRange are basically categorical variabels, I   
   changed their datatype till categorical

 - The bar chart of the Prosper Score showed that there are customers in the data set that have a score of 11 which      should not be possible since the score just ranges from 1-10 which I cleaned (removed them from the dataset)

 - around 1000 loans have a monthly payment of 0 which doesnt really make sense but might be related to some special 
   arrangement (for example: the customer does not need to pay back the loan during the first 6 months). Therefore, I 
   decided to the keep these values in the dataset.



## Bivariate Exploration

As mentoined, I am interested in the relationship between certain variables and the outcome of the loan (current status of the loan). So I will now plot the variables of interest against the outcome of the loan. 
Since the we have both categorical and numeric in the data set, I will plot those seperatly: first part with numeric variables (I plot a violinplot and a boxplot for each variable) and then in the second part wiht the 


#### Part 1: Numeric Variabales

```{python}
#plotting the monthy loan payment with a violinplot and a boxplot against LoanStatus 
plt.figure(figsize = [25, 18])

plt.subplot(2, 2, 1)
sb.boxplot(data = loan_data_clean, x = 'LoanStatus', y = 'MonthlyLoanPayment', color = base_color, order = loan_data_clean['LoanStatus'].value_counts().index)
plt.xticks(rotation=45)
plt.xlabel('Status of the Loan')
plt.ylabel('Monthly Loan Payments')

plt.subplot(2, 2, 2)
sb.violinplot(data = loan_data_clean, x = 'LoanStatus', y = 'MonthlyLoanPayment', color = base_color, order = loan_data_clean['LoanStatus'].value_counts().index)
plt.xticks(rotation=45)
plt.xlabel('Status of the Loan')
plt.ylabel('Monthly Loan Payments');
```

```{python}
#plotting Recommendations with a violinplot and a boxplot against LoanStatus 
plt.figure(figsize = [25, 18])

plt.subplot(2, 2, 1)
sb.boxplot(data = loan_data_clean, x = 'LoanStatus', y = 'Recommendations', color = base_color, order = loan_data_clean['LoanStatus'].value_counts().index)
plt.xticks(rotation=45)
plt.xlabel('Status of the Loan')
plt.ylabel('Recommendations')

plt.subplot(2, 2, 2)
sb.violinplot(data = loan_data_clean, x = 'LoanStatus', y = 'Recommendations', color = base_color, order = loan_data_clean['LoanStatus'].value_counts().index)
plt.xticks(rotation=45)
plt.xlabel('Status of the Loan')
plt.ylabel('Recommendations');
```

```{python}
#plotting BorrowerRate (interest rate) with a violinplot and a boxplot against LoanStatus 
plt.figure(figsize = [25, 18])

plt.subplot(2, 2, 1)
sb.boxplot(data = loan_data_clean, x = 'LoanStatus', y = 'BorrowerRate', color = base_color, order = loan_data_clean['LoanStatus'].value_counts().index)
plt.xticks(rotation=45)
plt.xlabel('Status of the Loan')
plt.ylabel('Interest Rate')

plt.subplot(2, 2, 2)
sb.violinplot(data = loan_data_clean, x = 'LoanStatus', y = 'BorrowerRate', color = base_color, order = loan_data_clean['LoanStatus'].value_counts().index)
plt.xticks(rotation=45)
plt.xlabel('Status of the Loan')
plt.ylabel('Interest Rate');
```

```{python}
#plotting LoanOriginalAmount (Original Loan Amount) with a violinplot and a boxplot against LoanStatus 
plt.figure(figsize = [25, 18])

plt.subplot(2, 2, 1)
sb.boxplot(data = loan_data_clean, x = 'LoanStatus', y = 'LoanOriginalAmount', color = base_color, order = loan_data_clean['LoanStatus'].value_counts().index)
plt.xticks(rotation=45)
plt.xlabel('Status of the Loan')
plt.ylabel('Original Loan Amount')

plt.subplot(2, 2, 2)
sb.violinplot(data = loan_data_clean, x = 'LoanStatus', y = 'LoanOriginalAmount', color = base_color, order = loan_data_clean['LoanStatus'].value_counts().index)
plt.xticks(rotation=45)
plt.xlabel('Status of the Loan')
plt.ylabel('Original Loan Amount');
```

```{python}
#plotting OpenCreditLines (Open Credit Lines) with a violinplot and a boxplot against LoanStatus 
plt.figure(figsize = [25, 18])

plt.subplot(2, 2, 1)
sb.boxplot(data = loan_data_clean, x = 'LoanStatus', y = 'OpenCreditLines', color = base_color, order = loan_data_clean['LoanStatus'].value_counts().index)
plt.xticks(rotation=45)
plt.xlabel('Status of the Loan')
plt.ylabel('Original Loan Amount')

plt.subplot(2, 2, 2)
sb.violinplot(data = loan_data_clean, x = 'LoanStatus', y = 'OpenCreditLines', color = base_color, order = loan_data_clean['LoanStatus'].value_counts().index)
plt.xticks(rotation=45)
plt.xlabel('Status of the Loan')
plt.ylabel('Open Credit Lines');
```

```{python}
#plotting TotalProsperPaymentsBilled (On time Payments) with a violinplot and a boxplot against LoanStatus 
plt.figure(figsize = [25, 18])

plt.subplot(2, 2, 1)
sb.boxplot(data = loan_data_clean, x = 'LoanStatus', y = 'TotalProsperPaymentsBilled', color = base_color, order = loan_data_clean['LoanStatus'].value_counts().index)
plt.xticks(rotation=45)
plt.xlabel('Status of the Loan')
plt.ylabel('On time Payments')

plt.subplot(2, 2, 2)
sb.violinplot(data = loan_data_clean, x = 'LoanStatus', y = 'TotalProsperPaymentsBilled', color = base_color, order = loan_data_clean['LoanStatus'].value_counts().index)
plt.xticks(rotation=45)
plt.xlabel('Status of the Loan')
plt.ylabel('On time Payments');
```

#boxplotting all numeric variabels against LoanStatus 
plt.figure(figsize = [25, 50])

plt.subplot(6, 2, 1)
sb.boxplot(data = loan_data_clean, x = 'LoanStatus', y = 'MonthlyLoanPayment', color = base_color, order = loan_data_clean['LoanStatus'].value_counts().index)
plt.xticks(rotation=45)
plt.xlabel('Status of the Loan')
plt.ylabel('Monthly Loan Payments')

plt.subplot(6, 2, 2)
sb.boxplot(data = loan_data_clean, x = 'LoanStatus', y = 'Recommendations', color = base_color, order = loan_data_clean['LoanStatus'].value_counts().index)
sounts().index)
plt.xticks(rotation=45)
plt.xlabel('Status of the Loan')
plt.ylabel('Recommendations')

plt.subplot(6, 2, 3)
sb.boxplot(data = loan_data_clean, x = 'LoanStatus', y = 'BorrowerRate', color = base_color, order = loan_data_clean['LoanStatus'].value_counts().index)
plt.xticks(rotation=45)
plt.xlabel('Status of the Loan')
plt.ylabel('Interest Rate')

plt.subplot(6, 2, 4)
sb.boxplot(data = loan_data_clean, x = 'LoanStatus', y = 'LoanOriginalAmount', color = base_color, order = loan_data_clean['LoanStatus'].value_counts().index)
plt.xlabel('Status of the Loan')
plt.ylabel('Original Loan Amount')

plt.subplot(6, 2, 5)
sb.boxplot(data = loan_data_clean, x = 'LoanStatus', y = 'OpenCreditLines', color = base_color, order = loan_data_clean['LoanStatus'].value_counts().index)
plt.xticks(rotation=45)
plt.xlabel('Status of the Loan')
plt.ylabel('Open Credit Lines')

plt.subplot(6, 2, 6)
sb.boxplot(data = loan_data_clean, x = 'LoanStatus', y = 'TotalProsperPaymentsBilled', color = base_color,order = loan_data_clean['LoanStatus'].value_counts().index)
plt.xticks(rotation=45)
plt.xlabel('Status of the Loan')
plt.ylabel('On time Payments');


#now I also plot all numeric variabels against LoanStatus in form of violinplots
plt.figure(figsize = [25, 50])

plt.subplot(6, 2, 1)
sb.violinplot(data = loan_data_clean, x = 'LoanStatus', y = 'MonthlyLoanPayment', color = base_color, order = loan_data_clean['LoanStatus'].value_counts().index)
plt.xticks(rotation=45)
plt.xlabel('Status of the Loan')
plt.ylabel('Monthly Loan Payments')

plt.subplot(6, 2, 2)
sb.violinplot(data = loan_data_clean, x = 'LoanStatus', y = 'Recommendations', color = base_color, order = loan_data_clean['LoanStatus'].value_counts().index)
plt.xticks(rotation=45)
plt.xlabel('Status of the Loan')
plt.ylabel('Recommendations')

plt.subplot(6, 2, 3)
sb.violinplot(data = loan_data_clean, x = 'LoanStatus', y = 'BorrowerRate', color = base_color, order = loan_data_clean['LoanStatus'].value_counts().index)
plt.xticks(rotation=45)
plt.xlabel('Status of the Loan')
plt.ylabel('Interest Rate')

plt.subplot(6, 2, 4)
sb.violinplot(data = loan_data_clean, x = 'LoanStatus', y = 'LoanOriginalAmount', color = base_color, order = loan_data_clean['LoanStatus'].value_counts().index)
plt.xticks(rotation=45)
plt.xlabel('Status of the Loan')
plt.ylabel('Original Loan Amount')

plt.subplot(6, 2, 5)
sb.violinplot(data = loan_data_clean, x = 'LoanStatus', y = 'OpenCreditLines', color = base_color, order = loan_data_clean['LoanStatus'].value_counts().index)
plt.xticks(rotation=45)
plt.xlabel('Status of the Loan')
plt.ylabel('Open Credit Lines')

plt.subplot(6, 2, 6)
sb.violinplot(data = loan_data_clean, x = 'LoanStatus', y = 'TotalProsperPaymentsBilled', color = base_color, order = loan_data_clean['LoanStatus'].value_counts().index)
plt.xticks(rotation=45)
plt.xlabel('Status of the Loan')
plt.ylabel('On time Payments');


#### Part 2: Categorical Variabales

```{python}
print(loan_data_clean.info())
```

```{python}
#plotting Term (length of the Loan) variabels against LoanStatus with help of a clusterd bar chart
plt.figure(figsize = [20,10])
sb.countplot(data = loan_data_clean, x = 'LoanStatus', hue = 'Term', order = loan_data_clean['LoanStatus'].value_counts().index)
plt.legend(loc = 1, ncol = 3, title = 'Length of the Loan (in month)')
plt.xticks(rotation = 25)
plt.xlabel('Status of the Loan');
```

```{python}
#plotting EmploymentStatus (Status of Employment) against LoanStatus with help of a heat map
plt.figure(figsize = [20,10])
sb.countplot(data = loan_data_clean, x = 'LoanStatus', hue = 'EmploymentStatus', order = loan_data_clean['LoanStatus'].value_counts().index)
plt.legend(loc = 1, ncol = 8, title = 'Status of Employment')
plt.xticks(rotation = 25)
plt.xlabel('Status of the Loan');

```

```{python}
#plotting EmploymentStatus (Status of Employment) against LoanStatus with help of a heat map
plt.figure(figsize = [20,10])
sb.countplot(data = loan_data_clean, x = 'LoanStatus', hue = 'IncomeRange', order = loan_data_clean['LoanStatus'].value_counts().index)
plt.legend(loc = 1, ncol = 8, title = 'Status of Employment')
plt.xticks(rotation = 25)
plt.xlabel('Status of the Loan');
```

```{python}
#plotting ProsperScore against LoanStatus with help of a heat map

# In the first step I need to reshape the data to
ct_counts_2 = loan_data_clean.groupby(['LoanStatus', 'ProsperScore']).size()
ct_counts_2 = ct_counts_2.reset_index(name = 'count')
ct_counts_2 = ct_counts_2.pivot(index = 'ProsperScore', columns = 'LoanStatus', values = 'count')
ct_counts_2
```

```{python}
#plotting ProsperScore against LoanStatus with help of a heat map
plt.figure(figsize = [15,7])
sb.heatmap(ct_counts_2, annot = True, fmt = 'd', cmap='Blues')
plt.xlabel('Status of the Loan')
plt.ylabel('Prosper Score');
```

### Talk about some of the relationships you observed in this part of the investigation. How did the feature(s) of interest vary with other features in the dataset?

> Your answer here!

### Did you observe any interesting relationships between the other features (not the main feature(s) of interest)?

> Your answer here!


## Multivariate Exploration

> Create plots of three or more variables to investigate your data even
further. Make sure that your investigations are justified, and follow from
your work in the previous sections.

```{python}

```

### Talk about some of the relationships you observed in this part of the investigation. Were there features that strengthened each other in terms of looking at your feature(s) of interest?

> Your answer here!

### Were there any interesting or surprising interactions between features?

> Your answer here!


> At the end of your report, make sure that you export the notebook as an
html file from the `File > Download as... > HTML` menu. Make sure you keep
track of where the exported file goes, so you can put it in the same folder
as this notebook for project submission. Also, make sure you remove all of
the quote-formatted guide notes like this one before you finish your report!


### Engineering a new variable

```{python}
print(loan_data_clean.StatedMonthlyIncome.head())
print(loan_data_clean.MonthlyLoanPayment.head())
```

```{python}
# in the first step I create a new variable ratio_income_loanPayment
loan_data_clean['ratio_income_loanPayment'] = (loan_data_clean.MonthlyLoanPayment / loan_data_clean.StatedMonthlyIncome)*100
# round the ratio to 2 decimals
loan_data_clean['ratio_income_loanPayment'] = loan_data_clean['ratio_income_loanPayment'].round(2)
print(loan_data_clean['ratio_income_loanPayment'].sample(3))
print(loan_data_clean['ratio_income_loanPayment'].describe())
```

One can see from the statisitcs that there are null values and values generate by dividing by zero

```{python}
loan_data_clean.StatedMonthlyIncome.value_counts().head(20)
```

```{python}
loan_data_clean.MonthlyLoanPayment.value_counts().head(20)
```
